version: "3.2"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env/.env.dev
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "8080:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env/.env.dev

volumes:
  pgdata:
